jobs:
  fsa_insider_trading:
    enabled: true
    # Job scheduling
    cron_expression: "0 1 * * *"  # Run daily at 1 AM
    
    # Web scraper configuration
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    requests_per_minute: 10
    timeout: 30
    random_delay: true
    
    # Transformer configuration
    transformer_type: "fsa"
    transformer_config: {}
    
    # Loader configuration
    loader_type: "iceberg"
    loader_config:
      spark_config:
        spark.jars.packages: "org.apache.iceberg:iceberg-spark-runtime-3.3_2.12:1.3.0"
        spark.sql.catalog.spark_catalog: "org.apache.iceberg.spark.SparkSessionCatalog"
        spark.sql.catalog.spark_catalog.type: "hive"
        spark.driver.memory: "4g"
        spark.executor.memory: "4g"
      catalog_name: "hive_prod"
      warehouse_location: "/warehouse/tablespace/external/hive"
    
    # Data destination
    database: "financial_data"
    table: "insider_trading"
    
    # Job persistence
    db_url: "sqlite:///jobs.sqlite"